baseURL = "https://ckevin.fr/"
title = "C. Kevin"
languageCode = "fr"
hasCJKLanguage = false
theme = "hugo-theme-monochrome"
enable_toc = true
enable_collapsible_toc = true # default: false
[params]
footer = "Copyright © 2025 by C.Kevin" # default: Non
hide_navbar_on_scroll = true
enable_math = true # default: false
home = ["HTML", "RSS", "JSON"]
enable_site_search = true # default: false
author = "Kevin" # default: no author `meta` tag
enable_twitter_cards = false # default: true
color_scheme = "light" # "light" or "dark"

  [param.syntax_highlight]
  lib = "builtin" # "builtin" | "prism.js" (default: "builtin")
    [param.syntax_highlight.builtin]
    enable_code_copy = true # default: true




[[menu.navbar]]
identifier = "about"
name = "À propos de moi"
title = "about"
url = "/about/"
weight = 5


[[menu.navbar]]
identifier = "categories"
name = "Catégories"
url = "/categories/"
weight = 2

[[menu.navbar]]
identifier = "tags"
name = "Tags"
title = "Tags"
url = "/tags/"
weight = 3

[[menu.navbar]]
identifier = "home"
name = "Accueil"
title = "Accueil"
url = "/"
weight = 1
