baseURL = "https://ckevin.fr/"
title = "C. Kevin"
languageCode = "fr-fr"
defaultContentLanguage = "fr-fr"
hasCJKLanguage = false
theme = "hugo-theme-monochrome"
enableEmoji = true
enableGitInfo = true
enable_header_anchor = true

[pagination]
pagerSize = 7

[params]
footer = "Copyright © 2024 - 2025 by C.Kevin" # default: Non
hide_navbar_on_scroll = true
enable_math = true # default: false
home = ["HTML", "RSS", "JSON"]
enable_site_search = true # default: false
author = "Kevin" # default: no author `meta` tag
enable_twitter_cards = false # default: true
color_scheme = "light" # "light" or "dark"
enable_toc = true
enable_collapsible_toc = true # default: false
enable_header_anchor = true # default: true
dateFormat = "2 Jan 2006"

[ param.author]
  name = "Kevin"
  email = "blog@ckevin.fr"

  [param.syntax_highlight]
  lib = "builtin" # "builtin" | "prism.js" (default: "builtin")
    [param.syntax_highlight.builtin]
    enable_code_copy = true # default: true
  [params.list_layout]
  enable_group_by_year = false # default: true
  enable_show_date = true # default: true
  enable_pagination = false # default: false



[[menu.navbar]]
identifier = "about"
name = "À propos de moi"
title = "about"
url = "/about/"
weight = 5


[[menu.navbar]]
identifier = "categories"
name = "Catégories"
url = "/categories/"
weight = 2

[[menu.navbar]]
identifier = "tags"
name = "Tags"
title = "Tags"
url = "/tags/"
weight = 3

[[menu.navbar]]
identifier = "posts"
name = "Posts"
title = "Posts"
url = "/posts/"
weight = 1

[goldmark.renderer]
unsafe= true

[highlight]
anchorLineNos = false
codeFences = false
guessSyntax = false
hl_Lines = ""
lineAnchors = ""
lineNoStart = 1
lineNos = false
lineNumbersInTable = true
noHl = false
noClasses = true
style = "monokai"
tabWidth = 4

[module]

  [[module.imports]]

    path = 'github.com/hugomods/icons/vendors/bootstrap'

  [[module.imports]]

    path = 'github.com/hugomods/icons/vendors/font-awesome'
  [[module.imports]]

    path = 'github.com/hugomods/icons/vendors/feather'

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[outputs]
home = ["HTML", "RSS", "JSON"]



